jsk-ros-pkg/jsk_control

- jsk_calibration/euslisp/calibration.l
see discussion in https://github.com/jsk-ros-pkg/jsk_control/pull/194
> [jsk_calibration] Fix robust-motion bug and not use it as default

- jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
- jsk_footstep_controller/src/footcoords.cpp
[jsk_footstep_coords] Do not update transformation between ground and odom on ground during dual leg stance phase
> [jsk_footstep_coords] Do not update transformation between ground and odom on ground during dual leg stance phase

- jsk_footstep_controller/README.md
- jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
- jsk_footstep_controller/src/footcoords.cpp
see https://github.com/jsk-ros-pkg/jsk_control/issues/201
> [jsk_footstep_controller] transform force vector to specified frame_id in footcoords

- jsk_calibration/euslisp/hrp2-calibration.l
The class hrp2w-calibration-config is a replica function of hrp2jsknt except with changes to the calibration board coordinates.
> Updated to generate motion for hrp2w model

- eus_qpoases/Makefile.qpOASES
fix for https://github.com/jsk-ros-pkg/jsk_control/issues/213
> [eus_qpoases] Support ccache

- jsk_footstep_planner/launch/hrp2jsk_footprint.launch
> [jsk_footstep_planner] Add publisher of polygon of footprint for HRP2JSK

- jsk_footstep_planner/euslisp/footstep-snapper.l
- jsk_footstep_planner/euslisp/footstep_planner_util.l
- jsk_footstep_planner/euslisp/simple_occupancy_grid.l
It's too slow, I will write cpp version
> [jsk_footstep_planner] Snap geometry_msgs::PoseStamped (from rviz) onto grid map

- jsk_footstep_planner/euslisp/simple_occupancy_grid.l
> [jsk_footstep_planner] Do not check if the footstep can be placable on plane across planes

- jsk_footstep_planner/euslisp/footstep_planner_util.l
> [jsk_footstep_planner] Use quaternion-from-two-vectors to compute rotate in project-coords-on-to-plane

- jsk_footstep_controller/euslisp/lookaround-ground.l
* Streching knee 
* specify wait pitch directly
* Based on :reset-pose
> [jsk_footstep_controller] Update pose to look ground

- jsk_footstep_planner/config/hrp2jsk_param.l
- jsk_footstep_planner/euslisp/footstep-planner-node.l
- jsk_footstep_planner/euslisp/footstep_planner.l
- jsk_footstep_planner/euslisp/simple_occupancy_grid.l
1. Move
successors a little bit when projecting footprint to different level 
2. Use footstep coordinate rather than mid-coords of the footstep as goal
coordinates
> [jsk_footstep_planner] Improve planning for different levels:

- jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
- jsk_footstep_controller/src/footcoords.cpp
Just update contact states from force sensors
It may conceal the problem of https://github.com/start-jsk/rtmros_common/issues/690
> [jsk_footstep_controller] Update ground and odom_on_ground periodically rather than synchronizing with force sensors.

- jsk_teleop_joy/launch/vehicle.launch
- jsk_teleop_joy/plugin.xml
- jsk_teleop_joy/src/jsk_teleop_joy/plugin/vehicle.py
@orikuma 
PS3 controller version for vehicle handling like mario-cart
> [jsk_teleop_joy] Add joystick program for vehicle

- jsk_footstep_controller/euslisp/footstep-controller.l
- jsk_footstep_planner/config/hrp2jsk_param.l
- jsk_footstep_planner/euslisp/footstep-planner-node.l
- jsk_footstep_planner/euslisp/footstep_planner.l
- jsk_footstep_planner/euslisp/simple_occupancy_grid.l
Let me roll it...
Completely not tested on robot
> [jsk_footstep_planner, jsk_footstep_controller] Support rolling terrain,

- eus_qpoases/catkin.cmake
unless setting dependencies between target in CMakeLists.txt and Makefile.qpOASES, it may happens build failure by chance.
> [eus_qpoases] add dependencies to libqpOASES

- eus_qpoases/CMakeLists.txt
- eus_qpoases/catkin.cmake
- eus_qpoases/euslisp/test-eus-qpoases.l
- eus_qpoases/package.xml
- eus_qpoases/test/eus-qpoases.test.l
- eus_qpoases/test/eus_qpoases.test
> Eus qpoases test

- jsk_footstep_controller/scripts/footstep_visualizer.py
> [jsk_footstep_controller] Add new script to visualize cop of each leg

- jsk_footstep_controller/scripts/footstep_visualizer.py
> [jsk_footstep_controller/footstep_visualizer] Reverse position of left and right

- jsk_footstep_controller/scripts/footstep_visualizer.py
> [jsk_footstep_controller/footstep_visualizer] Visualize zmp

- eus_qpoases/euslisp/eus-qpoases.l
> Add debug print check

- eus_qpoases/euslisp/eus-qpoases.l
- eus_qpoases/euslisp/test-eus-qpoases.l
- eus_qpoases/test/eus-qpoases.test.l
> Add eus qp check status

- eus_qp/CMakeLists.txt
- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/package.xml
- eus_qp/test/test_contact_wrench_opt.l
- eus_qp/test/test_contact_wrench_opt.test
Add euslisp qp application for contact wrench optimization.
Add function definitions, sample codes, and rostest codes.
> Add contact opt application

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/test/test_contact_wrench_opt.l
Update contact wrench.
Fix codes and tests and add samples.
Support min-max limitation constraint.
> Update contact wrench

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/test/test_contact_wrench_opt.l
Add codes to allow min inequality boundary violation.
Add samples and update rostest.
> Add violation

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_projection_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/package.xml
- jsk_footstep_planner/src/footstep_state.cpp
Add sample program to project footprint directly on pointcloud.
```
rosrun jsk_footstep_planner footstep_projection_demo
```
> [jsk_footstep_planner] Implement FootstepState and projection to pointtcloud

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_planning_2d_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/include/jsk_footstep_planner/graph.h
- jsk_footstep_planner/src/footstep_graph.cpp
2D footstep planning is implemented in C++. almost same to the euslisp version.
```
rosrun jsk_footstep_planner footstep_planning_2d_demo
```
> [jsk_footstep_planner] 2D footstep planning is implemented in C++

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_planning_2d_demo.cpp
- jsk_footstep_planner/demo/footstep_projection_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state_discrete_close_list.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_state.cpp
- jsk_footstep_planner/src/footstep_state_discrete_close_list.cpp
Introduce special close list class called `FootstepStateDiscreteCloseList`.
FootstepStateDiscreteCloseList provides `O(1)` computational complexity to searching and inserting.
now we can plan footsteps under 0.1 sec if the goal is within 2m from start state.
Memo:
In graph search algorithm, we cannot add nodes to open list which are already in close list.
It is easy to find whether node is already closed or not if graph structure is static.
However, our graph structure is dynamic (we dynamically expand graph tree in footstep planning because the tree structure may be too large).
In this case, we always search node in close list.
If we implement this search in array (`std::vector`), the computation time is `O(n)`.
OTH, solver has a lot of inserting for the close list.
According these …
> [jsk_footstep_planner] Use FootstepStateDiscreteCloseList for close list

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_planning_2d_interactive_demo.cpp
demonstration of 2d planning
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B4bnoIcbRJVuYUpPb1B4ckx1cjA/view?usp=sharing
> [jsk_footstep_planner] Interactive demo of C++ footstep planner

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_planning_2d_interactive_demo.cpp
- jsk_footstep_planner/demo/footstep_projection_demo.cpp
- jsk_footstep_planner/src/footstep_state.cpp
> [jsk_footstep_planner] Add demo for curved surface

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/demo/footstep_projection_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/best_first_search_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/include/jsk_footstep_planner/solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/solver_node.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_state.cpp
You can plan footsteps in 0.1 sec on planar -3~3m region.
We optimized perception phase by lazy-perception-in-planning technique:
1) Do not detect planar region before planning
2) Do not detect planar region until accurate pose of footstep is
required
3) use 2.5D pointcloud to get candidate pointcloud which footstep is placed on
> [jsk_footstep_planner] implement Planning with pointcloud model 

- jsk_footstep_planner/demo/footstep_planning_2d_demo.cpp
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_state.cpp
```
rosrun jsk_footstep_planner footstep_planning_2d_perception_demo _model:=hills
```
```
rosrun jsk_footstep_planner footstep_planning_2d_perception_demo _model:=slope
```
> [jsk_footstep_planner] Add demonstration of footstep planning over curved and sloped surface

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/bench/bench_footstep_planning_without_perception.cpp
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
Add code to take bench of footstep planing without perception
> [jsk_footstep_planning] Add program to bench footstep planning speed

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/bench/bench_footstep_planning_with_perception.cpp
- jsk_footstep_planner/bench/bench_footstep_planning_without_perception.cpp
- jsk_footstep_planner/bench/bench_util.h
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/scripts/plot_bench.py
Easily understanding [-3, 3]m planning is under 0.2 sec
> [jsk_footstep_planner] Add script to plot bench result

- jsk_footstep_planner/demo/footstep_planning_2d_interactive_demo.cpp
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/demo/footstep_projection_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_state.cpp
verify footstep on a pointcloud model
> [jsk_footstep_planner] Check pointcloud model supports footprint

- jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/include/jsk_footstep_planner/solver_node.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_state.cpp
success of projection to pointcloud
> [jsk_footstep_planner] Implement local movement if footstep is close to

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state_discrete_close_list.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_state.cpp
> [jsk_footstep_planning] Visualize open and close list as pointcloud

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/cfg/FootstepPlanner.cfg
- jsk_footstep_planner/demo/footstep_planning_2d_demo.cpp
- jsk_footstep_planner/demo/footstep_planning_2d_interactive_demo.cpp
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_planner.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/include/jsk_footstep_planner/util.h
- jsk_footstep_planner/launch/sample/footstep_planner_sample.launch
- jsk_footstep_planner/launch/sample/footstep_planner_sample.rviz
- jsk_footstep_planner/package.xml
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_planner.cpp
- jsk_footstep_planner/src/footstep_planner_node.cpp
- jsk_footstep_planner/src/footstep_state.cpp
```
roslaunch jsk_footstep_planner footstep_planner_sample.launch
```
> [jsk_footstep_planner] Add actionlib interface to C++ version of footstep planner. and add simplest smaple

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/cfg/PointCloudModelGenerator.cfg
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_planner.h
- jsk_footstep_planner/include/jsk_footstep_planner/pointcloud_model_generator.h
- jsk_footstep_planner/launch/sample/footstep_planner_perception_sample.launch
- jsk_footstep_planner/launch/sample/footstep_planner_perception_sample.rviz
- jsk_footstep_planner/src/footstep_planner.cpp
- jsk_footstep_planner/src/pointcloud_model_generator.cpp
- jsk_footstep_planner/src/pointcloud_model_generator_node.cpp
```
roslaunch jsk_footstep_planner footstep_planner_perception_sample.launch
```
> [jsk_footstep_planner] Add perception sample with actionlib interface

- jsk_footstep_planner/cfg/FootstepPlanner.cfg
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_planner.h
- jsk_footstep_planner/src/footstep_planner.cpp
> [jsk_footstep_planner] Update pointcloud to show close list and open list during planning

- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_planner.cpp
- jsk_footstep_planner/src/footstep_state.cpp
- jsk_footstep_planner/src/pointcloud_model_generator.cpp
> [jsk_footstep_planner] Just use kdtree nearest search in checking

- jsk_footstep_planner/launch/heightmap_perception/heightmap.launch
- jsk_footstep_planner/launch/heightmap_perception/heightmap_viewer.launch
Mapping using robot centristic heightmap
> [jsk_footstep_planner] Add launch file for heightmap mapping

- jsk_footstep_planner/include/jsk_footstep_planner/footstep_planner.h
- jsk_footstep_planner/src/footstep_planner.cpp
> [jsk_footstep_planner] Add text information on rviz

- jsk_footstep_planner/launch/cppplanner/optimistic_footstep_planner.launch
- jsk_footstep_planner/launch/eusplanner/example.launch
- jsk_footstep_planner/launch/eusplanner/example_6d.launch
- jsk_footstep_planner/launch/eusplanner/example_drc_task2.launch
- jsk_footstep_planner/launch/eusplanner/example_heuristic.launch
- jsk_footstep_planner/launch/eusplanner/footstep_successors_visualization.launch
- jsk_footstep_planner/launch/heightmap_perception/heightmap.launch
Visualized using furutaractive 
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B4bnoIcbRJVueGhxcV9PUEk2UWc/view?usp=sharing
> [jsk_footstep_planner] Add launch file to run footstep planner with heightmap integration

- jsk_footstep_controller/euslisp/gui-client.l
- jsk_footstep_planner/config/footstep_buttons.yaml
- jsk_footstep_planner/launch/cppplanner/footstep_planner.rviz
- jsk_footstep_planner/launch/cppplanner/optimistic_footstep_planner.launch
> [jsk_footstep_planner, controller] Add rviz GUI set for playing with footstep planner

- eus_qp/euslisp/contact-optimization.l
- eus_qpoases/euslisp/eus-qpoases.l
- eus_qpoases/euslisp/test-eus-qpoases.l
- eus_qpoases/src/eus_qpoases.cpp
- eus_qpoases/test/eus-qpoases.test.l
Add LP solver using qpOASES.
Add tests and samples.
> Add LP solver using qpOASES

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
Add no-contact constraint and tests
> Add no-contact constraint and tests

- eus_qp/euslisp/model-predictive-control.l
- eus_qp/euslisp/test-model-predictive-control.l
- eus_qp/test/test_model_predictive_control.l
- eus_qp/test/test_model_predictive_control.test
- eus_qpoases/euslisp/eus-qpoases.l
Add Model Predictive Control (nagasaka'2012).
Add classes, examples, and test codes.
> Add Model Predictive Control

- jsk_footstep_planner/bench/bench_footstep_planner.cpp
footstep before taking benchmark
> [jsk_footstep_planner/bench_footstep_planner] Project start and goal

- jsk_footstep_planner/scripts/plot_bench.py
Usage:
```
$ ./plot_bench.py -h                                                              
usage: plot_bench.py [-h] [--image-suffix IMAGE_SUFFIX] [--min MIN]
[--max MAX]
csv_file
Plot benchmark result csv
positional arguments:
csv_file              csv file
optional arguments:
-h, --help            show this help message and exit
--image-suffix IMAGE_SUFFIX
suffix to save image
--min MIN             minimum value
--max MAX             maximum value
```
Generate image like below:
> [jsk_footstep_planner] Save to eps figure when visualizing benchmark plot

- jsk_footstep_planner/config/model_sample.rviz
- jsk_footstep_planner/launch/sample/model_sample.launch
> [jsk_footstep_planner] Add simple launch file to preview models for benchmarking

- jsk_footstep_controller/euslisp/root-height.l
determine-best-weight-height-from-footcoords は
waistのつもりで誤ってweightと書いていました．
> [jsk_footstep_controller] fix function name. weight -> root

- jsk_footstep_planner/src/pointcloud_model_generator.cpp
> [jsk_footstep_planner] Update stair model to more difficult one

- jsk_footstep_controller/scripts/stabilizer_watcher.py
on the ground at the first frame
> [jsk_footstep_controller] Publish /odom_init_trigger when robot stands

- jsk_footstep_controller/euslisp/root-height.l
neutral footsteps
200mm difference
> [jsk_footstep_controller] Publish plotting data when computing root height

- jsk_footstep_controller/euslisp/root-height.l
- jsk_footstep_controller/euslisp/sample-root-height.l
- jsk_footstep_controller/sample/sample_root_height.launch
```
roslaunch jsk_footstep_controller sample_root_height.launch
```
> [jsk_footstep_controller] Add sample launch file for root-height.l

- jsk_footstep_planner/demo/footstep_planning_2d_interactive_demo.cpp
- jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
- jsk_footstep_planner/demo/footstep_projection_demo.cpp
These commits are forgotten in previous commit.
> [jsk_footstep_planner] Do not use jsk_pcl_ros, use jsk_recognition_utils instead of it.

- jsk_ik_server/scripts/plot_ik_grid.py
> [jsk_ik_server] Script to visualize reachability in heatmap manner

- jsk_footstep_controller/euslisp/lookaround-ground.l
tilt がいないときに、サービスを呼ばないようにしました。
multisenseのlaserを使わないときようです。
> not call service if tilt is absent

- jsk_footstep_planner/launch/heightmap_perception/heightmap.launch
> change static polygon param

- jsk_teleop_joy/scripts/joy_relative_converter.py
b-controlのようなスライダの駆動ができないnanokontrol2のようなmidiコントローラのために、起動時のスライダの位置を中央と見なして値を変換するノードを追加。
> Joy relative

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/model-predictive-control.l
- eus_qp/euslisp/test-model-predictive-control.l
Fix bug of mpc inequality-matrix contact coords and update samples.
> Fix bug of mpc inequality-matrix contact coords and update samples.

- eus_qp/euslisp/model-predictive-control.l
Return world input value (wrench).
> Return world input value (wrench).

- contact_states_observer/CMakeLists.txt
- contact_states_observer/euslisp/contact-states-client.l
- contact_states_observer/euslisp/contact-states-observer.l
- contact_states_observer/euslisp/grasp-client.l
- contact_states_observer/launch/contact_grasp_states_publisher.launch
- contact_states_observer/msg/GraspReferenceData.msg
- contact_states_observer/msg/GraspState.msg
- contact_states_observer/msg/GraspStates.msg
- contact_states_observer/msg/OREContactState.msg
- contact_states_observer/msg/OREContactStates.msg
- contact_states_observer/package.xml
@garaemon 
Move contact state observer package from jsk-ros-pkg-unreleased.
> Move contact state observer package from jsk-ros-pkg-unreleased

- eus_qp/euslisp/model-predictive-control.l
Support output variables in evaluation.
> Support output variables in evaluation

- jsk_teleop_joy/scripts/joy_relative_converter.py
[jsk_teleop_joy/scripts/joy_relative_converter.py] fix bug to support buttons
> fix joy_relative_converter

- jsk_footstep_planner/euslisp/footplace_planner_for_manipulation.l
https://github.com/jsk-ros-pkg/jsk_control/issues/501
argsのoptionを増やしました。
> add args for ik with standcoords

- jsk_footstep_planner/euslisp/footplace_planner_for_manipulation.l
* すべてthreshold以内に入ったらループが終わるように
* ikが解けなかったらwarnpの文章が適切に出るように
#503
> Debug like fullbodyik

- jsk_footstep_planner/euslisp/footplace_planner_for_manipulation.l
You can add :collision-check-robot-link-list and so on
> [jsk_footstep_planner] Add &allow-other-keys to fullbody-inverse-kinematics-with-standcoords.

- jsk_footstep_controller/scripts/footstep_visualizer.py
> [jsk_footstep_controller/footstep_visualizer] Add Reference capture point and Actual capture point  and draw text

- contact_states_observer/euslisp/contact-states-observer.l
Update for thk hand for jaxon.
> Update for thk hand for jaxon.

- jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h
- jsk_footstep_planner/src/footstep_graph.cpp
- jsk_footstep_planner/src/footstep_planner.cpp
- jsk_footstep_planner/src/footstep_state.cpp
> [jsk_footstep_planner] Measure perception duration in collaborative perception-planning scheduling

- jsk_footstep_controller/scripts/footstep_visualizer.py
draw a margined convex hull with white color
> get leg_vertices from StabilizerService param

- contact_states_observer/euslisp/contact-states-observer.l
Add :init for contact state topic initialization.
> Add :init for contact state topic initialization

- jsk_footstep_controller/CMakeLists.txt
- jsk_footstep_controller/cfg/FootstepVisualizer.cfg
- jsk_footstep_controller/package.xml
- jsk_footstep_controller/scripts/footstep_visualizer.py
And fix some error about tf conversion and nan computation
> [footstep_visualizer] Support dynamic_reconfigure API to toggle which point to draw.

- eus_qp/euslisp/model-predictive-control.l
Fix typos in MPC drift and output ports.
> Fix typos in MPC drift and output ports.

- jsk_footstep_planner/src/footstep_planner.cpp
Modified:
- jsk_footstep_planner/src/footstep_planner.cpp
> [jsk_footstep_planner] Do not check pointcloud if no perception mode

- jsk_footstep_planner/package.xml
Re-create PR to pass the test.
Modified:
- jsk_footstep_planner/package.xml
> [jsk_footstep_planner] Fix genjava problem with message_generation as build_depend (#512)

- jsk_footstep_planner/src/footstep_graph.cpp
stride in heuristic estimation
Modified:
- jsk_footstep_planner/src/footstep_graph.cpp
> [jsk_footstep_planner] Only consider forward step

- eus_qpoases/euslisp/eus-qpoases.l
Use concatenate matrix functions  and fix checking of ineq and eq existence
> Use concatenate matrix functions  and fix checking of ineq and eq existence

- .travis.yml
See https://github.com/jsk-ros-pkg/jsk_control/pull/554#issuecomment-177754735
> [.travis.yml] set travis test parallel -j1

- jsk_calibration/jaxon_calibration/capture_data/hardware_config/cam_config.yaml
Modified:
- jsk_calibration/jaxon_calibration/capture_data/hardware_config/cam_config.yaml
> [jsk_calibration] Update camera config parameter for JAXON

- eus_qp/euslisp/contact-optimization.l
Add max fz for default contact
> Add max fz for default contact

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/cfg/FootstepMarker.cfg
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_conversions.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/include/jsk_footstep_planner/marker_array_publisher.h
- jsk_footstep_planner/launch/sample/footstep_planner_marker_sample.launch
- jsk_footstep_planner/src/footstep_conversions.cpp
- jsk_footstep_planner/src/footstep_marker.cpp
- jsk_footstep_planner/src/marker_array_publisher.cpp
> [jsk_footstep_marker] Move footstep_marker from jsk_interactive_marker

- eus_qp/euslisp/contact-optimization.l
Enable to set jacobi from arg.
> Enable to set jacobi from arg.

- eus_qp/euslisp/contact-optimization.l
Generate drawing object when drawing (https://github.com/jsk-ros-pkg/jsk_control/pull/558).
> Generate drawing object when drawing

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/euslisp/test-model-predictive-control.l
Fix updating of drawing-object.
Add mu/cop margin ratio argument.
Add hand gripper contacts.
Update tests.
> Fix add hand constraint

- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/src/footstep_marker.cpp
Modified:
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/src/footstep_marker.cpp
> [jsk_footstep_planner] Support projection from marker

- jsk_footstep_controller/euslisp/robot-boundingbox.l
/robot_bbox was seemed not to be used
> [jsk_footstep_controller] Publish robot_bbox only when analysis_level is whole_links

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/test/test_contact_wrench_opt.l
Add function to calculate wrench from given wrench.
Currently calculation with contact constraints does not work.
@YoheiKakiuchi , @otsubo
> Add function to calculate wrench from given wrench.

- eus_qp/euslisp/contact-optimization.l
6次元min-maxの制約のdrawing-objectに球をセットするようにしました．
> [eus_qp] add :gen-drawing-object method to 6d-min-max-contact-constraint

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/test/test_contact_wrench_opt.l
Add argument to support equaliry error for wrench/torque distribution.
> Add argument to support equaliry error

- eus_qpoases/euslisp/eus-qpoases.l
- eus_qpoases/euslisp/test-eus-qpoases.l
- eus_qpoases/src/eus_qpoases.cpp
- eus_qpoases/test/eus-qpoases.test.l
> Add hotstart of eus_qpoases

- eus_qp/euslisp/contact-optimization.l
Enable to set solve-qp-mode. 
Default value is same as solve-qpoases-qp function
> Enable to set solve-qp-mode. 

- eus_qp/euslisp/model-predictive-control.l
Add argument to switch solve-qp-mode for qpoases
> Add argument to switch solve-qp-mode for qpoases

- .travis.rosinstall.hydro
- .travis.yml
- .travis_before_script_jsk_recognition_utils.bash
- jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
- jsk_footstep_controller/launch/floor_detection.launch
- jsk_footstep_controller/src/footcoords.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch
- jsk_footstep_planner/src/footstep_marker.cpp
- jsk_teleop_joy/plugin.xml
- jsk_teleop_joy/src/jsk_teleop_joy/plugin/joy_footstep_marker.py
please merge after https://github.com/jsk-ros-pkg/jsk_control/pull/577 and https://github.com/jsk-ros-pkg/jsk_recognition/pull/1576 .
Default behavior is same as before.
> Project odom_init to detected floor

- eus_qp/euslisp/model-predictive-control.l
- eus_qp/euslisp/test-model-predictive-control.l
- eus_qp/test/test_model_predictive_control.l
Update receding horizon proc count.
> Update receding horizon proc count

- jsk_footstep_controller/euslisp/jaxon-footstep-controller.l
- jsk_footstep_controller/euslisp/util.l
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch
- jsk_footstep_planner/src/footstep_marker.cpp
Footstepの指定を一回だけでなく、連続的に追加していけるように修正しました。
> [jsk_footstep_planner] update footstep_marker for appending footsteps continuously

- jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch
- jsk_footstep_planner/src/footstep_planner.cpp
normalを使うためのlaunchの変更と、footstepのsuccessorを修正しました。
https://github.com/jsk-ros-pkg/jsk_control/pull/610
https://github.com/jsk-ros-pkg/jsk_control/pull/608
> [footstep_planner] add parameter default_rfoot_to_lfoot_offset

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_conversions.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/src/footstep_conversions.cpp
- jsk_footstep_planner/src/footstep_marker.cpp
目的座標が回転している時に、stepの変換がおかしいのを直しました。
> [footstep_marker] fix foot coordinates for rotated pose

- eus_qp/euslisp/contact-optimization.l
- eus_qp/euslisp/test-contact-wrench-opt.l
- eus_qp/test/test_contact_wrench_opt.l
Add linearlized friction cone.
(symmetric and arbitrary division number)
Add test codes.
> Add linearlized friction cone

- eus_qp/euslisp/contact-optimization.l
Add additional-inequality-matrix  and additional-inequality-min-vector
> Add additional-inequality-matrix  and additional-inequality-min-vector

- jsk_footstep_controller/scripts/stabilizer_watcher.py
Modified stabilizer_watcher's standing interval time.
hrp2が地面に不安定な状態で立たせていると，
robot stands on the groundを連呼するので，
intervalを設けました．
> [jsk_footstep_controller] Modified stabilizer_watcher

- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state_discrete_close_list.h
This is a range violation of volume_key.
> [jsk_footstep_planner] fix bug in FootstepStateDiscreteCloseList

- jsk_footstep_planner/launch/heightmap_perception/heightmap.launch
related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/1886
> [jsk_footstep_planner] update launch for JAXON_RED

- .travis.rosinstall.hydro
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_planner.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state.h
- jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch
- jsk_footstep_planner/src/footstep_marker.cpp
- jsk_footstep_planner/src/footstep_planner.cpp
- jsk_footstep_planner/src/footstep_state.cpp
Offset between end-coords and center of cube is represented in Footstep.msg.
https://github.com/jsk-ros-pkg/jsk_common_msgs/pull/12
> [footstep_planner/footstep_marker] fix offset 

- jsk_footstep_planner/include/jsk_footstep_planner/solver_node.h
- jsk_footstep_planner/src/ann_grid.cpp
- jsk_footstep_planner/src/footstep_marker.cpp
- jsk_footstep_planner/src/footstep_planner.cpp
see
- https://github.com/jsk-ros-pkg/jsk_common/pull/1462
- https://github.com/jsk-ros-pkg/jsk_common/issues/1461
> Stop using deprecated jsk_topic_tools/log_utils.h

- jsk_footstep_planner/README.md
- jsk_footstep_planner/config/HRP2JSKNTS_footstep_planner_params.yaml
- jsk_footstep_planner/config/HRP2JSKNT_footstep_planner_params.yaml
- jsk_footstep_planner/config/JAXON_RED_footstep_planner_params.yaml
- jsk_footstep_planner/euslisp/footstep-planner-client-sample.l
- jsk_footstep_planner/launch/cppplanner/optimistic_footstep_planner.launch
- jsk_footstep_planner/test/test_footstep_planning_eus_client.test
- envを使わずargを使うようにしました
- footstep plannerのパラメタをyamlファイルから読み込むようにしました。
- HRP2JSKNT, HRP2JSKNTSようファイルをなんとなくで作って見ました
> Update footstep planner sample (update parameters)

- jsk_footstep_planner/euslisp/generate-footstep-planner-parameters-from-robot-model.l
footstepのsuccessorなどのパラメタいくつかを、ロボットモデルから自動生成するものを作りました。
> Add generator for some footstep planner parameters using robot model

- jsk_footstep_controller/euslisp/util.l
footstepをeusからおくるときの足幅パラメタもeusmodelから決定するようにしました。
> Set lfoot rfoot offset based on robot model.

- .travis.rosinstall.hydro
- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/package.xml
Add footstep planner rostest.
https://github.com/jsk-ros-pkg/geneus/issues/51
https://github.com/jsk-ros-pkg/jsk_control/pull/643
> Add footstep planner rostest.

- jsk_footstep_planner/config/sample_robot_footstep_planner_params.yaml
- jsk_footstep_planner/src/footstep_planner.cpp
offsetがあるときに、end-effectorのステップの差分が、successorの指定とずれる問題を解決した。
> Fix successor offset

- jsk_footstep_planner/config/HRP2JSKNT_footstep_planner_params.yaml
- jsk_footstep_planner/config/JAXON_footstep_planner_params.yaml
Update HRP2JSKNT, HRP2JSKNTS footstep planner params and add parameter for JAXON.
> Update HRP2JSKNT, HRP2JSKNTS footstep planner params and add parameter for JAXON.

- contact_states_observer/README.md
- contact_states_observer/euslisp/contact-states-observer.l
Add contact state observer readme and update roseus rate.
> Add contact state observer readme

- eus_qp/CMakeLists.txt
- eus_qp/package.xml
- eus_qpoases/CMakeLists.txt
- eus_qp : add missing install directory, also create libeus_qp.so under {PROJECT_SOURCE_DIR}/lib
- eus_qpoases : add missing install directory
> add missing install command to CMakeLists.txt

- eus_qp/euslisp/cfr-cwc-calculation.l
Update dcfr obj env constraint.
> Update dcfr obj env constraint

- eus_qp/README.md
[eus_qp/README.md] Add readme for eus_qp and euslisp programs.
> [eus_qp/README.md] Add readme for eus_qp and euslisp programs.

- eus_qpoases/CMakeLists.txt
rebased version of #581 (@kwmrmsy, @wkentaro)
> Set include path of qpoases in eus_qpoases

- contact_states_observer/euslisp/contact-states-observer.l
Check length of data list in contact states observer publishing parts.
> [contact_states_observer] Check length of data list in contact states observer publishing parts.

- jsk_footstep_controller/src/footcoords.cpp
> [jsk_footstep_contorller] Do not publish odom tf when publish_odom_tf param is false

- jsk_footstep_planner/launch/heightmap_perception/heightmap.launch
add pass through filter for creating heightmap in order to remove points of a ceiling
> [jsk_footstep_planner] add pass through filter

- jsk_footstep_planner/CMakeLists.txt
- jsk_footstep_planner/cfg/FootstepMarker.cfg
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_planner.h
- jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch
- jsk_footstep_planner/src/footstep_marker.cpp
- jsk_footstep_planner/src/footstep_planner.cpp
- jsk_footstep_planner/srv/SetHeuristicPath.srv
* fix launch
* add use_default_step_as_goal to footstep_marker in order to avoid error accumulation using end-coords on TF
> Update footstep planner

- .travis.yml
- cmd_vel_smoother/CMakeLists.txt
- cmd_vel_smoother/README.md
- cmd_vel_smoother/cfg/CmdVelSmoother.cfg
- cmd_vel_smoother/launch/cmd_vel_smoother.launch
- cmd_vel_smoother/package.xml
- cmd_vel_smoother/src/cmd_vel_smoother.cpp
This is revised version of https://github.com/jsk-ros-pkg/jsk_control/pull/480
Please see [README.md](https://github.com/furushchev/jsk_control/blob/3c2fb953c44228e27d1f38319e4e90e12395f042/cmd_vel_smoother/README.md) for detail
> add cmd_vel_smoother package

- .travis.yml
- jsk_footstep_controller/CMakeLists.txt
> add missing install directories

- eus_qp/optmotiongen/euslisp/instant-configuration-task.l
Support to set different scale value for each posture joint.
> [eus_qp/optmotiongen] add target-posture-scale-list argument

- jsk_teleop_joy/src/jsk_teleop_joy/joy.py
- jsk_teleop_joy/src/jsk_teleop_joy/joy_status.py
This change add support towards ipega controller ([PG-9083](http://ipega.hk/gamehandle/53-98.html)).
> Add ipega controller support

- jsk_footstep_controller/CMakeLists.txt
forget to install config directory, see https://github.com/start-jsk/rtmros_hrp2/pull/534
> [jsk_footstep_controller] install config

- .travis.yml
- jsk_footstep_controller/src/footcoords.cpp
- jsk_footstep_planner/include/jsk_footstep_planner/footstep_state_discrete_close_list.h
> add melodic support

- jsk_control/package.xml
add url in package.xml of jsk_control
> [jsk_control] add url in package.xml of jsk_control

- jsk_ik_server/scripts/ik-grid/hrp2.sh
- jsk_ik_server/scripts/ik-grid/pr2.sh
`plot_ik_grid_one.py` is not found in this repo
> [jsk_ik_server] fix typo in hrp2.sh and pr2.sh

- joy_mouse/package.xml
this PR add python3 deps in joy_mouse for noetic.
this PR also changes to the format 3.
> [joy_mouse] update joy_mouse python3 deps for noetic

- jsk_teleop_joy/CMakeLists.txt
- jsk_teleop_joy/configs/launchpad_x.yaml
Support Novation LAUNCHPAD X MIDI pad controller
requires 
- https://github.com/jsk-ros-pkg/jsk_control/pull/788
> [jsk_teleop_joy][MIDI] Support LAUNCHPAD X
