jsk-ros-pkg/jsk_control

jsk_teleop_joy/launch/hrp2_trackball_head.launch
jsk_teleop_joy/launch/pr2_trackball_head.launch

Related to https://github.com/jsk-ros-pkg/jsk_control/pull/187.
from @otsubo 
```
staroのfieldcomputerで，このスレッドの手順にしたがって環境構築をして，デバイスをさしてdrc_task_common.launchを上げたのですが
unused args [DEV] for include of [/home/leus/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_teleop_joy/launch/robot_trackball_head.launch]
というエラーが出てしまいます．
どこを修正すれば動作するでしょうか？
```

remove DEV argument for trackball

---

eus_qp/CMakeLists.txt
eus_qp/package.xml
eus_qp/src/qp_lib.cpp

Eigen3 on indigo may not provide Eigen::internal::sqrt
Eigen::internal::abs, in order to provide them, we define these function in qp_lib.cpp
before including qp stuff.
https://github.com/jsk-ros-pkg/jsk_control/issues/208

[eus_qp] Fix for indigo. 

---

jsk_footstep_planner/euslisp/footstep_planner.l
jsk_footstep_planner/euslisp/footstep_planner_util.l

@snozawa 
for example, 
```
(send-all (project-coords-on-to-plane
(make-coords) (send (make-cube 100 100 100) :faces)
(float-vector 0 0 1))
:draw-on :flush t)
```

[jsk_footstep_planner] separate standalone utility functions into footstp_planner_util.l

---

jsk_footstep_planner/euslisp/footstep_planner_util.l

[jsk_footstep_planner] Use mtimer instead of ros::time-now

---

jsk_footstep_planner/euslisp/footstep-planner-node.l
jsk_footstep_planner/euslisp/footstep_planner.l
jsk_footstep_planner/euslisp/footstep_planner_util.l
jsk_footstep_planner/euslisp/simple_occupancy_grid.l

Much faster than hash-table implementation, almost 100 times faster

[jsk_footstep_planner] Optimize creation of occupancy-grid by using integer-vector rather than hash-table

---

jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
jsk_footstep_controller/src/footcoords.cpp

```
odom ---> BODY --> ground (midcoords of the legs)
+---> odom_on_ground
```
We use the same transformation about odom -> odom_on_ground to BODY -> ground.
It's simpler implementation than before but it work.
However it cannot compute correct **ground** coordinates during single stance phase.

	[jsk_footste_controller] Fix odom_on_ground consistency but ignore correctness during single stance phase

---

jsk_footstep_controller/euslisp/footstep-controller.l
jsk_footstep_planner/config/hrp2jsk_param.l

Change gait generator parameters according to plane condition including pitch angle and taking into account if transition is upward or downward.
Plane condition is one of :rolling, :pitch-up, :pitch-down and :horizontal.
Height transition is upward, downward or none.
These means `4x4x3=48` patterns to change parameters.
It's too hacky and we should use pointcloud data to compute swing-height.

[jsk_footstep_controller] Change gait generator parameters according to plane condition and height difference

---

eus_qpoases/catkin.cmake

solves jsk-ros-pkg/jsk_control#349

Added install rules for qpoases headers and libs to catkin cmake-file.

---

eus_qpoases/euslisp/eus-qpoases.l

Print debug message by default. If you want to disable it, :debug nil

Print debug message by default. If you want to disable it, :debug nil

---

eus_qp/euslisp/contact-optimization.l
eus_qp/euslisp/test-contact-wrench-opt.l

摩擦力を受けながら並進方向に滑る場合の制約条件です．
```
(instance 2D-translational-sliding-contact-constraint :init 10 :norm-axis :z slide-axis :x)
```
とすると，x正方向に滑っている制約条件として，
摩擦係数10で，x負方向に最大摩擦力ちょうどの力がかかっている，y方向に最大摩擦以内の力がかかっている，ような制約条件ができます．
（内部向け：このPRは euslib/demo/murooka/fullbody_holding/contact-constraint-extension.l の一部を整理したものです．）

[eus_qp] add translational sliding constraint

---

jsk_footstep_controller/catkin.cmake
jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
jsk_footstep_controller/msg/FootCoordsLowLevelInfo.msg
jsk_footstep_controller/msg/SynchronizedForces.msg
jsk_footstep_controller/src/footcoords.cpp

* Publish synchronized forces from foot_coords subscribe it from foot_coords internally.
* Update alpha (low pass filter parameter) to 0.1 from 0.5.
* Update queue length not to drop messages.

[jsk_footstep_controller] Publish synchronized forces from foot_coords

---

jsk_footstep_controller/CMakeLists.txt
jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
jsk_footstep_controller/msg/SynchronizedForces.msg
jsk_footstep_controller/package.xml
jsk_footstep_controller/src/footcoords.cpp

Three types of naive algorithm are implemented:
1) Estimate support leg from force sensors and keep support leg during double stance phase
2) Estimate support leg from force sensors and change support leg during double stance phase by leg forces
3) Estimate support leg from force sensors and change support leg during double stance phase by zmp
These naive algorithms are not so good.
for example, walk JAXON in the current spot with 16 steps and it estimates as 20mm forward but it actually moves 64mm forward.

[jsk_footstep_controller] Add odometry estimation based on leg kinematics

---

jsk_footstep_planner/CMakeLists.txt
jsk_footstep_planner/bench/bench_footstep_planning_with_perception.cpp
jsk_footstep_planner/bench/bench_footstep_planning_without_perception.cpp
jsk_footstep_planner/bench/bench_util.h
jsk_footstep_planner/demo/footstep_planning_2d_interactive_demo.cpp
jsk_footstep_planner/demo/footstep_planning_2d_perception_demo.cpp
jsk_footstep_planner/include/jsk_footstep_planner/best_first_search_solver.h
jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h
jsk_footstep_planner/include/jsk_footstep_planner/footstep_state_discrete_close_list.h
jsk_footstep_planner/scripts/plot_bench.py
jsk_footstep_planner/src/footstep_graph.cpp
jsk_footstep_planner/src/footstep_state_discrete_close_list.cpp

1. Do not use Eigen::Affine3f::rotation because it calls SVD internally.
2. Do not cast to Eigen::AngleAxisf, just use cos(w/2) to compute angle
from quaternion.
1 is important because our planner is 10 times faster than before.

[jsk_footstep_planner] Re-implement footstepHeuristicStepCost in     computationally-efficient way.

---

jsk_footstep_planner/cfg/PointCloudModelGenerator.cfg
jsk_footstep_planner/include/jsk_footstep_planner/pointcloud_model_generator.h
jsk_footstep_planner/src/pointcloud_model_generator.cpp
jsk_footstep_planner/src/pointcloud_model_generator_node.cpp

Left is a pointcloud with ~hole_rate=40.0 in height map representation and
right one is noise-reduced height map by morphological filtering.

[jsk_footstep_planner] Add ~hole_rate to simulate hole in pointcloud

---

jsk_footstep_controller/include/jsk_footstep_controller/footcoords.h
jsk_footstep_controller/src/footcoords.cpp

DO NOT USE THIS FRAME FOR PERCEPTION AND PLANNING because the timestamp is not reliable
It's just for visualization.
You can visualize trajectory of zmp by jsk_rviz_plugins/TFTrajectory on rviz.
movie only for jsk members
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B4bnoIcbRJVuY09XYjNMY2ZjemM/view?usp=sharing

[jsk_footstep_controller/footcoords] Publish zmp as tf for visualization

---

jsk_footstep_controller/euslisp/root-height.l

Original version is implemented by @mmurooka 
and interface of function is modified to use as library.
```lisp
(load "root-height.l")
(load "package://hrpsys_ros_bridge_tutorials/euslisp/hrp2jsknt-interface.l")
(setq *robot* (instance hrp2jsknt-robot :init))
(objects (list *robot*))
(test-root-height-all)
```

[jsk_footstep_controller] Compute root-link height according to torque and manipulability. 

---

eus_nlopt/euslisp/nlopt.l
eus_nlopt/include/nlopt_solver.h
eus_nlopt/src/nlopt_solver.cpp
eus_nlopt/src/nlopt_wrapper.cpp

いくつかのソルバで，収束計算の閾値が正しくセットされていなかったので直しました．
また，解放されない値がソルバ内にあったので，解放するようにしました．

use ftol xtol values in coresolver initialization

---

jsk_ik_server/euslisp/ik-evaluation.l

Currently only position and mean of pdf is taken into account.
Planning time is 0.03 sec.
```lisp
(do-until-key (test-stand-location-planning (make-coords :pos (float-vector (random 1000.0) (random 1000.0) (+ 900 (random 1000.0))))))
```

[jsk_ik_server] Implement stand location planning based on continuous ik grid

---

jsk_footstep_planner/include/jsk_footstep_planner/simple_neighbored_graph.h

In some environment, build fails.
```bash
In file included from /home/furushchev/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/src/simple_neighbored_graph.cpp:36:0:
/home/furushchev/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/include/jsk_footstep_planner/simple_neighbored_graph.h:73:17: error: field 'name_' has incomplete type
/home/furushchev/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/include/jsk_footstep_planner/simple_neighbored_graph.h: In constructor 'jsk_footstep_planner::SimpleNeighboredNode::SimpleNeighboredNode(const string&)':
/home/furushchev/ros/hydro/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/include/jsk_footstep_planner/simple_neighbored_graph.h:49:52: error: class 'jsk_footstep_planner::SimpleNeighboredNode' does not have …
```

[jsk_footstep_planner/simple_neighbored_graph.h] add missing include string

---

contact_states_observer/euslisp/contact-states-observer.l

Check result symbol which has "success" in its name

[contact_states_observer] Support multiple success states.

---

eus_qp/3rdparty/eiquadprog.hpp
eus_qp/CMakeLists.txt

reported from https://github.com/ros/rosdistro/pull/9733#issuecomment-152794343
this works ok on gcc 4.8 but fails on 4.6 at http://jenkins.ros.org/view/IbinT64/job/ros-indigo-eus-qp_binarydeb_trusty_amd64/270/console
- 6185f34 [3rdparty/eiquadprog.hpp] using std::abs instead of internal::abs
- 349f279 CMakeLists.txt: using test as execute name may confuse system

fix compile error:

---

eus_qp/euslisp/model-predictive-control.l
eus_qp/euslisp/test-model-predictive-control.l

Update mpc to fix calculation for drift and output matrices.
Update test functions.

Update mpc to fix calculation for drift and output matrices

---

eus_qp/CMakeLists.txt
eus_qp/package.xml
eus_qp/src/qp_lib.cpp

Revert eus_qp qp_lib.cpp Eigen usage hack by @garaemon ,
because we can build this program on travis without this hack (https://github.com/jsk-ros-pkg/jsk_control/commit/4937ac04d0c1beceb8c4c92eac258c00549943f9) 
and this program itself is not related with ros program.
In addition, recently eus_qp travis build cannot succeed
https://s3.amazonaws.com/archive.travis-ci.org/jobs/112049705/log.txt
```
[eus_qp] Scanning dependencies of target eus_qp                                 
[eus_qp] [ 50%] [100%] Building CXX object CMakeFiles/eus_qp.dir/src/qp_lib.cpp.o 
[eus_qp] Building CXX object CMakeFiles/euq_qp_test.dir/src/example.cpp.o       
[eus_qp] /workspace/ros/ws_jsk_control/src/jsk_control/eus_qp/src/qp_lib.cpp:6:24: fatal error: ros/common.h: No such file or directory 
[eus_qp] …
```

Revert eus_qp qp_lib.cpp Eigen usage hack

---

eus_qp/euslisp/contact-optimization.l

@snozawaさん，
`(wrench-distribute-from-total-wrench)` などの関数のdebugオプションを
`(solve-eiquadprog)`に渡すようにしました．
以下の2点でデフォルトの挙動がこれまでと同じように保たれていることを確認しています．
1.
https://github.com/jsk-ros-pkg/jsk_control/blob/master/eus_qpoases/euslisp/eus-qpoases.l#L58 で，
debugがデフォルトtでこれが使われていましたので，
`(wrench-distribute-from-total-wrench)`のdebugのデフォルトもtにしました．
2.
https://github.com/jsk-ros-pkg/jsk_control/blob/master/eus_qp/euslisp/contact-optimization.l#L20
で`(solve-eiquadprog)`を選択してもエラーにならないように，
`(solve-eiquadprog)`に`&allow-other-keys`を加えました．

[eus_qp/euslisp] pass debug option to qp solve function.

---

eus_qp/euslisp/contact-optimization.l
eus_qp/euslisp/test-contact-wrench-opt.l

力・モーメントの上下限を指定する contact constraintのクラスを追加しました．
1次元片側の`calc-constraint-param-list-for-min-max`が，
6次元 & 両側 なので，12個並んだ制約になります．

[eus_qp/euslisp] add 6d-min-max-contact-constraint class and test

---

eus_qp/euslisp/contact-optimization.l
eus_qp/euslisp/test-contact-wrench-opt.l

@snozawa さん，多角形領域に圧力中心が入っている制約のクラスとテストを追加しました．
default-contact-constraint で，contact-face引数を与えると，
l-min, l-maxから長方形領域の圧力中心条件が作られる代わりに，
faceの多角形領域の圧力中心条件が作られます．
デフォルトの挙動は変わりません．

[eus_qp/euslisp] add polygon-cop-contact-constraint

---

jsk_calibration/hrp2jsknts_calibration/README.md
jsk_calibration/hrp2w_calibration/estimate_params/config/system.yaml

In hrp2w_calibration, modify checkerboard spacing x,y parameters to be measurement values for actual checkerboard, and add this procedure to README.

[jsk_calibration] Modify checkerboard spacing values and modify README

---

jsk_footstep_planner/README.md
jsk_footstep_planner/include/jsk_footstep_planner/footstep_marker.h
jsk_footstep_planner/src/footstep_marker.cpp

footstep_plannerとfootstep_markerでfootstepの座標がずれていたのを修正しました。
plannterでは、四角形の中心をfootstepの座標として使っています。
markerでは、モデルのlleg/rlegのend-coordsを座標として使っています。
footstep_markerのパラメータ、lleg/rleg_footstep_offsetで調整します。

fix center position of footsteps

---

eus_qp/euslisp/model-predictive-control.l

Enable to add additional-inequality-matrix and additional-inequality-min-vector for MPC COG parameters

Enable to add additional-inequality-matrix and additional-inequality-min-vector for MPC COG parameters

---

jsk_footstep_controller/CMakeLists.txt
jsk_footstep_controller/action/GoPos.action
jsk_footstep_controller/euslisp/go-pos-client.l
jsk_footstep_controller/euslisp/go-pos-server.l
jsk_footstep_controller/euslisp/jaxon-footstep-controller.l
jsk_footstep_controller/euslisp/util.l

footstepを使ってgo-posするためのサーバー/クライアントを作りました。
いずれfootstep_markerに統合を目指しています。
```go-pos-server.l``` でサーバーを立ち上げて、以下のようにclientを使います。
clientではgo-posで目的地を上書きするときは明示的にoverwriteをつけるようにしています。
~~~
(load "package://jsk_footstep_controller/euslisp/go-pos-client.l")
(setq *gp* (instance go-pos-client :init))
(send *gp* :go-pos-no-wait 2 0 0)
(send *gp* :go-pos-no-wait 2 1 0 :overwrite t)
~~~

Add go-pos to footstep controller

---

jsk_footstep_controller/euslisp/go-pos-server.l
jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch

go posした時に、re-planningするかstepの微調整で留めるかを選択するようにしました。
```<param name="force_replanning" value="true" />```  にすると、必ず再プランニングします。

[jsk_footstep_controller] fix go-pos-server.l

---

jsk_footstep_controller/euslisp/go-pos-server.l
jsk_footstep_controller/euslisp/jaxon-footstep-controller.l
jsk_footstep_controller/euslisp/util.l
jsk_footstep_controller/launch/floor_detection.launch
jsk_footstep_planner/launch/JAXON_RED_footstep_planner_perception.launch
jsk_footstep_planner/launch/footstep_plane_detection.launch

This PR includes #629.
To deal with unstable footstep execution problem on the horizontal plane temporaly, run global plane estimation and project planned footprints onto them before :set-foot-steps.
This projection may work in terrain walking but it is only checked in horizontal plane walking.
Default behavior is not changed.
(This problem should be solved by localization or pointcloud accumulation layer but I cannot solve it by instant methods like using raw imu orientation, faster executing rate, filtering, matching points before accumulation and so on.)

Add plane projection option to go pos server

---

jsk_footstep_controller/euslisp/util.l
jsk_footstep_planner/euslisp/footstep-planner-client-sample.l
jsk_footstep_planner/launch/cppplanner/footstep_planner.rviz
jsk_footstep_planner/launch/cppplanner/optimistic_footstep_planner.launch
jsk_footstep_planner/src/footstep_graph.cpp
jsk_footstep_planner/test/test_footstep_planning_eus_client.l
jsk_footstep_planner/test/test_footstep_planning_eus_client.test

@YoheiKakiuchi さん
footstep plannerをeusから呼ぶサンプルを更新して、テストなどを追加しました。
各コミットは以下です。
- optimistic_footstep_planner.launchでuse_obstacle_modelできるようにしました（デフォルトfalse == 挙動かわらない）。またrvizでobstacleてんぐんを表示するようにしました
- use_lazy_perceptionのパラメタは、USE_PERCEPTION引数を使うようにしました（デフォルトtrue == 挙動かわらない）
- footstep client sampleの関数を、utilsに移動させて、関数名をながくてわかりやすくしました
- （jskeusglのsample_possionのかわり）簡易ですが、引数のbodiesから点群をつくるようにしました（内包をチェックしてる）
- footstep_graph.cppで、use_obstacle_modelがtrueでかつ点群サイズが０のときにセグフォしていたので、点群サイズが0のときにはisCollideをぬけて干渉ナシにするようにしました。
- testを追加して、cmakeでよばれるようにしました。

Update footstep planner sample

---

jsk_footstep_planner/euslisp/footstep_planner_util.l
jsk_footstep_planner/euslisp/robot-model-util.l
jsk_footstep_planner/package.xml

Some packages in jsk_visualization depends on jsk_pcl_ros because it uses the srv files.
But jsk_pcl_ros is a very large package and the dependency should be avoided ideally.
The solution is placing `msg/srv` files into `jsk_recognition_msgs`.
1. Merge this after `jsk_recognition_msgs` is released: http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_recognition_msgs
1. Release this pacakge.
1. Remove `jsk_pcl_ros/srv`.
1. Release `jsk_pcl_ros`.
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1914

Migrate srv files from jsk_pcl_ros to jsk_recognition_msgs

---

jsk_footstep_planner/config/sample_robot_footstep_planner_params.yaml
jsk_footstep_planner/euslisp/generate-footstep-planner-parameters-from-robot-model.l
jsk_footstep_planner/test/test_footstep_planning_eus_client.l
jsk_footstep_planner/test/test_footstep_planning_eus_client.test

https://github.com/jsk-ros-pkg/jsk_control/issues/650
をテストするためのサンプル関数をテスト関数に追加しました。
また、eusのsample-robotをテストとして使用するようにしました。
デフォルトは、自動生成footstep parameterから問題の箇所をコメントアウトしたものをコミットしています。
なので、テストは通ります。
```
#rleg_footstep_offset: [0.05, 0.0, 0.0]
#lleg_footstep_offset: [0.05, 0.0, 0.0]
```

Add test for fs successor

---

jsk_teleop_joy/src/jsk_teleop_joy/camera_view.py
jsk_teleop_joy/src/jsk_teleop_joy/joy_status.py
jsk_teleop_joy/src/jsk_teleop_joy/plugin/joy_pose_6d.py
jsk_teleop_joy/src/jsk_teleop_joy/plugin/joy_rviz_view_controller.py
jsk_teleop_joy/src/jsk_teleop_joy/plugin/rviz_view_controller_singleton.py

joyからrvizのviewを動かす機能について、修正及び機能追加をしました。
修正： pitch周りで1周すると向きが反転していた
　　　view controlが常にpublishされていた
rvizをマウスで動かした時のviewが反映されずに、joyで動かすとjoyで最後に動かした位置に戻っていた
機能追加： viewのリセットを追加

[jsk_teleop_joy] update view control in rviz using teleop_joy

---

jsk_teleop_joy/src/jsk_teleop_joy/plugin/joy_pose_6d.py

tf frame_ids should not start with "/", especially tf2

[jsk_teleop_joy] Remove / from default frame_id in pose6d plugin

---

eus_qp/euslisp/test-model-predictive-control.l

Add walking example by footstep list.
```
roseus
(load "package://eus_qp/euslisp/test-model-predictive-control.l")
(setup)
(length (setq *rs-list* (demo-mpc-gen-motion-5 :mu-trans 0.5)))
(length (setq *rs-list* (demo-mpc-gen-motion-5 :mu-trans 0.07)))
```

Add walking example by footstep list

---

jsk_footstep_planner/include/jsk_footstep_planner/footstep_astar_solver.h

Problem:
When a FootstepAstarSolver instance is generated with GraphT which has a different state type from FootstepState, a compilation error occurs because there are some hard-coded FootstepState::Ptr in its member functions.
Proposed solution:
I replaced hard-coded FootstepState::Ptr to StatePtr, which is defined in FootstepAstarSolver and equivalent to GraphT::StateT::Ptr, in order to refer the state type used in GraphT. I assume that the behavior of a FootstepAstarSolver with a FootstepGraph is not changed by this PR.

Replace FootstepState::Ptr to StatePtr in footstep_astar_solver to be used with a GraphT which has different state type

---

jsk_teleop_joy/CMakeLists.txt
jsk_teleop_joy/package.xml

to solve aapt-slow issues
c.f.  https://discourse.ros.org/t/preparing-for-indigo-sync-2018-05-14/4767/1, ros-infrastructure/ros_buildfarm#535

remove unused build_depends

---

jsk_footstep_planner/launch/heightmap_perception/heightmap.launch

元のプログラムで
roslaunch jsk_footstep_planner heightmap.launch
を呼ぶと
roslaunch file contains multiple nodes named [/heightmap_nodelet].
というエラーが出てしまうので、
それが出ないようにするための変更です。

fix heightmap launch so that it can work with nodelet.

---

eus_qp/optmotiongen/euslisp/inverse-kinematics-statics-wrapper.l
eus_qp/optmotiongen/euslisp/inverse-kinematics-wrapper.l
eus_qp/optmotiongen/euslisp/robot-environment.l
eus_qp/optmotiongen/euslisp/sample/sample-inverse-kinematics.l
eus_qp/optmotiongen/test/test-sample-inverse-kinematics.l

Add key arguments, `:root-virtual-joint-min-angle-list` and `:root-virtual-joint-max-angle-list` from inverse kinematics wrapper methods. Add tests of these arguments in travis test.
FYI @iory

[eus_qp/optmotiongen] support min/max angle of root virtual joint

---

eus_qp/optmotiongen/euslisp/sample/sample-inverse-kinematics-statics.l
eus_qp/optmotiongen/test/test-sample-inverse-kinematics-statics.l
eus_qp/optmotiongen/test/test-samplerobot.l

TravisがIndigoで通っていません．
https://travis-ci.org/jsk-ros-pkg/jsk_control/jobs/554074304
```
+ rosdep install -q -y --rosdistro indigo -n -q -r --ignore-src --from-paths /opt/ros/indigo/share .
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
eus_nlopt: Cannot locate rosdep definition for [nlopt]
eus_qpoases: Cannot locate rosdep definition for [rostest]
jsk_teleop_joy: Cannot locate rosdep definition for [image_view2]
rospack: Cannot locate rosdep definition for [cmake_modules]
....
```
https://github.com/jsk-ros-pkg/jsk_common/pull/1630 と同様に，jsk_travisをアップデートする必要がありそうです．

update jsk_travis 0.5.0

---

jsk_footstep_controller/scripts/stabilizer_watcher.py

robotsoundが
indigoからkineticに変わるときにSoundRequest型が変わり、
新たにvolumeというパラメータができました。
デフォルト値では音量0となってロボットが喋らないため、
volumeに値をセットしました。

[stabilizer_watcher.py]fix for kinetic

---

joy_mouse/package.xml

https://github.com/jsk-ros-pkg/jsk_control/pull/779/files changes rosdep key from python-pyudev to python-udev, which does not exists

jsk_mouse: fix wrong rosdep keys

---

jsk_teleop_joy/package.xml

`python-pygame` is Python 2 package.
We need to install `python3-pygame` instead on noetic.

[jsk_teleop_joy] python3-pygame is required on noetic
